### ISSUE TITLE
Cannot find module './constants'

### ISSUE THREAD

**Issue by timolins** [denizdogan/streamable-js#4]
`constants.js` doesn't end up in the `dist` directory which makes the module crash.

**Comment by denizdogan** [comment]
Thanks for reporting this, I've been really sloppy with the build process on this project. I normally use Webpack, but it has some strange issues with the har-validator library which is a dependency of request-promise.

Of course pull requests are welcome!

**Comment by denizdogan** [comment]
Fixed in 0.1.1
